# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161206_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=b' /static/profile_images'),
        ),
    ]
